/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplepaint;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author ASUS
 */
public class Paint extends javax.swing.JFrame implements MouseListener {
    
    private String shape="";
    private String color="";
    
    int points []= new int[4];
    int x,y;
    /**
     * Creates new form Paint
     */
    public Paint() {
        initComponents();
        this.addMouseListener(this);
        displayMode.setText("Pilih bangun dan warna dulu");
        btPutih.setBackground(Color.white);
        btHitam.setBackground(Color.black);
        btMerah.setBackground(Color.red);
        btKuning.setBackground(Color.yellow);
        btHijau.setBackground(Color.green);
        btBiru.setBackground(Color.blue);
        btPink.setBackground(Color.pink);
        btOranye.setBackground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbBangun = new javax.swing.ButtonGroup();
        BOARD = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        rbLingkaran = new javax.swing.JRadioButton();
        rbPersegi = new javax.swing.JRadioButton();
        pilihBangun = new javax.swing.JLabel();
        displayMode = new javax.swing.JLabel();
        pilihBangun1 = new javax.swing.JLabel();
        btPutih = new javax.swing.JButton();
        btMerah = new javax.swing.JButton();
        btKuning = new javax.swing.JButton();
        btHijau = new javax.swing.JButton();
        btHitam = new javax.swing.JButton();
        btBiru = new javax.swing.JButton();
        btPink = new javax.swing.JButton();
        btOranye = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BOARD.setBackground(new java.awt.Color(239, 237, 237));
        BOARD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BOARDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BOARDMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout BOARDLayout = new javax.swing.GroupLayout(BOARD);
        BOARD.setLayout(BOARDLayout);
        BOARDLayout.setHorizontalGroup(
            BOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        BOARDLayout.setVerticalGroup(
            BOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnClear.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        rbBangun.add(rbLingkaran);
        rbLingkaran.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        rbLingkaran.setText("Lingkaran");
        rbLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLingkaranActionPerformed(evt);
            }
        });

        rbBangun.add(rbPersegi);
        rbPersegi.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        rbPersegi.setText("Persegi");
        rbPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPersegiActionPerformed(evt);
            }
        });

        pilihBangun.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        pilihBangun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilihBangun.setText("Pilih Bangun");

        displayMode.setBackground(new java.awt.Color(255, 255, 255));
        displayMode.setFont(new java.awt.Font("Helvetica", 0, 10)); // NOI18N
        displayMode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        displayMode.setText("Display Mode");

        pilihBangun1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        pilihBangun1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pilihBangun1.setText("Pilih Warna");

        btPutih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPutihActionPerformed(evt);
            }
        });

        btMerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMerahActionPerformed(evt);
            }
        });

        btKuning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKuningActionPerformed(evt);
            }
        });

        btHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHijauActionPerformed(evt);
            }
        });

        btHitam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitamActionPerformed(evt);
            }
        });

        btBiru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBiruActionPerformed(evt);
            }
        });

        btPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPinkActionPerformed(evt);
            }
        });

        btOranye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOranyeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BOARD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayMode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbPersegi)
                                    .addComponent(pilihBangun1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pilihBangun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btHitam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBiru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPink)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btOranye))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btPutih)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMerah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btKuning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btHijau)))
                        .addGap(13, 13, 13))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BOARD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addComponent(pilihBangun)
                        .addGap(15, 15, 15)
                        .addComponent(rbLingkaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPersegi)
                        .addGap(18, 18, 18)
                        .addComponent(pilihBangun1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPutih, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMerah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btKuning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHijau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btHitam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBiru, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btOranye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayMode)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        rbBangun.clearSelection();
        this.color = "";
        this.shape = "";
        repaint();
        displayMode.setText("Clear, bangun dan warna kosong");
        points[0] = 0;
        points[1] = 0;
        points[2] = 0;
        points[3] = 0;
    }//GEN-LAST:event_btnClearActionPerformed

    private void rbLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLingkaranActionPerformed
        // TODO add your handling code here:
        if (rbLingkaran.isSelected()) {
            shape = "Lingkaran";
            displayMode.setText(shape + " " + color);
            repaint();
        }
    }//GEN-LAST:event_rbLingkaranActionPerformed

    private void rbPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPersegiActionPerformed
        // TODO add your handling code here:
        if (rbPersegi.isSelected()) {
            shape = "Persegi";
            displayMode.setText(shape + " " + color);
            repaint();
        }
    }//GEN-LAST:event_rbPersegiActionPerformed

    private void btPutihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPutihActionPerformed
        // TODO add your handling code here:
        color = "Putih";
        displayMode.setText(shape + " " + color);
        repaint();
    }//GEN-LAST:event_btPutihActionPerformed

    private void btMerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMerahActionPerformed
        // TODO add your handling code here:
        color = "Merah";
        displayMode.setText(shape + " " + color);
        repaint();
    }//GEN-LAST:event_btMerahActionPerformed

    private void btKuningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKuningActionPerformed
        // TODO add your handling code here:
        color = "Kuning";
        displayMode.setText(shape + " " + color);
        repaint();
    }//GEN-LAST:event_btKuningActionPerformed

    private void btHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHijauActionPerformed
        // TODO add your handling code here:
        color = "Hijau";
        displayMode.setText(shape + " " + color);
        repaint();
    }//GEN-LAST:event_btHijauActionPerformed

    private void btHitamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitamActionPerformed
        // TODO add your handling code here:
        color = "Hitam";
        displayMode.setText(shape + " " + color);
        repaint();
    }//GEN-LAST:event_btHitamActionPerformed

    private void btBiruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBiruActionPerformed
        // TODO add your handling code here:
        color = "Biru";
        displayMode.setText(shape + " " + color);
        repaint();
    }//GEN-LAST:event_btBiruActionPerformed

    private void btPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPinkActionPerformed
        // TODO add your handling code here:
        color = "Pink";
        displayMode.setText(shape + " " + color);
        repaint();
    }//GEN-LAST:event_btPinkActionPerformed

    private void btOranyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOranyeActionPerformed
        // TODO add your handling code here:
        color = "Oranye";
        displayMode.setText(shape + " " + color);
        repaint();
    }//GEN-LAST:event_btOranyeActionPerformed

    private void BOARDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOARDMousePressed
        // TODO add your handling code here:
        points[0] = 0;
        points[1] = 0;
        points[0] = evt.getX();
        points[1] = evt.getY();
        //System.out.println(points[0]);
        //System.out.println(points[1]);
        
    }//GEN-LAST:event_BOARDMousePressed

    private void BOARDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOARDMouseReleased
        // TODO add your handling code here:
        if (shape.equals("Persegi")){
            points[2] = 0;
            points[3] = 0;
            points[2] = evt.getX();
            points[3] = evt.getY();
            x = points[2] - points[0];
            y = points[3] - points[1];
            repaint();
        } else if (shape.equals("Lingkaran")) {
            points[2] = 0;
            points[3] = 0;
            points[2] = evt.getX();
            points[3] = evt.getY();
            x = points[2] - points[0];
            y = points[3] - points[1];
            repaint();
        }
    }//GEN-LAST:event_BOARDMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paint().setVisible(true);
            }
        });
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }
    
    public void paint(Graphics g) {
        super.paint(g);
        switch (color) {
            case "Putih"    : g.setColor(Color.white); break;
            case "Merah"    : g.setColor(Color.red); break;
            case "Kuning"   : g.setColor(Color.yellow); break;
            case "Hijau"    : g.setColor(Color.green); break;
            case "Hitam"    : g.setColor(Color.black); break;
            case "Biru"     : g.setColor(Color.blue); break;
            case "Pink"     : g.setColor(Color.pink); break;
            case "Oranye"   : g.setColor(Color.orange); break;
        }
        switch (shape) {
            case "Persegi"  : {
                if (points[0] > 0 & points[1] > 0 & points[2] > 0 & points[3] > 0) {
                    if (points[0] > points[2] && points[1] > points[3]) {
                    g.fillRect(points[2], points[3], Math.abs(x), Math.abs(y));
                } else if (points[0] < points[2] && points[1] > points[3]){
                    g.fillRect(points[0], points[3], Math.abs(x), Math.abs(y));
                } else if (points[0] > points[2] && points[1] < points[3]) {
                    g.fillRect(points[2], points[1], Math.abs(x), Math.abs(y));
                } else {
                    g.fillRect(points[0], points[1], Math.abs(x), Math.abs(y));
                    }
                }
            } break;
            case "Lingkaran": {
                int a=x;
                if (y>x) a=y;
                if (points[0] > 0 & points[1] > 0 & points[2] > 0 & points[3] > 0) {
                   if (points[0] > points[2] && points[1] > points[3]) {
                    g.fillOval(points[2], points[3], Math.abs(a), Math.abs(a));
                } else if (points[0] < points[2] && points[1] > points[3]){
                    g.fillOval(points[0], points[3], Math.abs(a), Math.abs(a));
                } else if (points[0] > points[2] && points[1] < points[3]) {
                    g.fillOval(points[2], points[1], Math.abs(a), Math.abs(a));
                } else {
                    g.fillOval(points[0], points[1], Math.abs(a), Math.abs(a));
                    } 
                }
            } break;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BOARD;
    private javax.swing.JButton btBiru;
    private javax.swing.JButton btHijau;
    private javax.swing.JButton btHitam;
    private javax.swing.JButton btKuning;
    private javax.swing.JButton btMerah;
    private javax.swing.JButton btOranye;
    private javax.swing.JButton btPink;
    private javax.swing.JButton btPutih;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel displayMode;
    private javax.swing.JLabel pilihBangun;
    private javax.swing.JLabel pilihBangun1;
    private javax.swing.ButtonGroup rbBangun;
    private javax.swing.JRadioButton rbLingkaran;
    private javax.swing.JRadioButton rbPersegi;
    // End of variables declaration//GEN-END:variables
}
